version: '4.1'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: orlanuzum/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/static/
      - media:/app/media/

  frontend:
    image: orlanuzum/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static/

  gateway:
    image: orlanuzum/foodgram_gateway
    env_file: .env
    depends_on:
      - frontend
      - backend
    ports:
      - 7000:80
    volumes:
      - static:/static/
      - media:/var/html/media

