version: '4'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: orlanuzum/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media

  frontend:
    image: orlanuzum/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/frontend_static

  nginx:
      image: orlanuzum/foodgram_gateway
      env_file: .env
      ports:
        - 7000:80
      volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
        - ../docs/:/usr/share/nginx/html/api/docs/
        - static:/static/
        - media:/var/html/media
      depends_on:
        - backend
